# Generated by Django 4.0.6 on 2022-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatars/default_avatar.jpg', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
