# Generated by Django 4.0.6 on 2022-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('m', 'manager'), ('d', 'driver'), ('c', 'client'), ('e', 'employee')], default='c', max_length=1, verbose_name='Роль'),
        ),
    ]
