# Generated by Django 4.0.6 on 2022-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.FileField(upload_to='documents/', verbose_name='Документ'),
        ),
    ]
