# Generated by Django 4.0.6 on 2022-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включено, когда аккаунт не в бане', verbose_name='Активный'),
        ),
    ]
