# Generated by Django 4.0.6 on 2022-07-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Марка')),
                ('model', models.CharField(max_length=128, verbose_name='Модель')),
                ('license_plate', models.CharField(max_length=10, verbose_name='Номер')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('engine_capacity', models.FloatField(verbose_name='Объем двигателя')),
                ('color', models.CharField(max_length=32, verbose_name='Цвет')),
                ('sts', models.CharField(max_length=10, verbose_name='СТС')),
                ('pts', models.CharField(max_length=15, verbose_name='ПТС')),
                ('car_class', models.CharField(choices=[('business', 'Бизнес'), ('standart', 'Стандарт')], max_length=12, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'car',
            },
        ),
    ]
