# Generated by Django 4.0.6 on 2022-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('business', 'Бизнес'), ('standart', 'Стандарт'), ('representative', 'Представительский'), ('minivan', 'Минивен'), ('minibus', 'Микроавтобус'), ('comfort', 'Комфорт'), ('bus', 'Автобус'), ('business_plus', 'Бизнес плюс'), ('cargo', 'Грузовой')], max_length=24, verbose_name='Класс'),
        ),
    ]
