# Generated by Django 4.0.6 on 2022-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_status_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('main', 'Основной'), ('spare', 'Запасной')], default='spare', max_length=12, verbose_name='Статус автомобиля'),
        ),
    ]
