# Generated by Django 2.2.27 on 2022-06-20 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='createion_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 10, 6, 50, 330452, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
