# Generated by Django 2.2.27 on 2022-06-20 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityFeed', '0002_auto_20220620_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='createion_date',
        ),
        migrations.AddField(
            model_name='news',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 10, 19, 36, 629390, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
