# Generated by Django 4.0.6 on 2022-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityFeed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='news/files/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='news/images/', verbose_name='Изображение'),
        ),
    ]
