# Generated by Django 4.0.5 on 2022-07-07 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityFeed', '0003_auto_20220620_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 19, 30, 11, 418441, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='news',
            name='styles',
            field=models.JSONField(null=True, verbose_name='Стили'),
        ),
    ]
