# Generated by Django 4.0.5 on 2022-07-08 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityFeed', '0004_remove_news_creation_date_news_date_news_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 10, 59, 57, 402437, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
