# Generated by Django 4.0.5 on 2022-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityFeed', '0008_alter_news_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='styles',
            field=models.JSONField(default=dict, verbose_name='Стили'),
        ),
    ]
