# Generated by Django 4.0.6 on 2022-08-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0004_remove_cityzone_prices_address_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceToCarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(choices=[('business', 'Бизнес'), ('standart', 'Стандарт')], max_length=32, verbose_name='Класс автомобиля')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена к классу',
                'verbose_name_plural': 'Цены к классам',
                'db_table': 'car_zone_price2car_class',
            },
        ),
        migrations.CreateModel(
            name='IntracityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('prices', models.ManyToManyField(to='tariffs.pricetocarclass', verbose_name='Цена к классу авто')),
                ('zone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.cityzone')),
            ],
            options={
                'verbose_name': 'Внутригородской тариф',
                'verbose_name_plural': 'Внутригородские тарифы',
                'db_table': 'intracity_tariff',
            },
        ),
    ]
