# Generated by Django 4.0.6 on 2022-09-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citytoprice',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='globaladdresstoprice',
            name='duration',
        ),
        migrations.AddField(
            model_name='citytoprice',
            name='hours_duration',
            field=models.IntegerField(default=-1, verbose_name='Часы'),
        ),
        migrations.AddField(
            model_name='citytoprice',
            name='minutes_duration',
            field=models.IntegerField(default=-1, verbose_name='Минуты'),
        ),
        migrations.AddField(
            model_name='globaladdresstoprice',
            name='hours_duration',
            field=models.IntegerField(default=-1, verbose_name='Часы'),
        ),
        migrations.AddField(
            model_name='globaladdresstoprice',
            name='minutes_duration',
            field=models.IntegerField(default=-1, verbose_name='Минуты'),
        ),
        migrations.AlterField(
            model_name='citytoprice',
            name='distance',
            field=models.FloatField(default=-1, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='globaladdresstoprice',
            name='distance',
            field=models.FloatField(default=-1, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='intercity_tariff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.intercitytariff', verbose_name='Межгородской тариф'),
        ),
    ]
