# Generated by Django 4.0.6 on 2022-08-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_alter_pricetocarclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intracitytariff',
            name='type',
            field=models.CharField(choices=[('default', 'Стандартный'), ('contract', 'Договор')], default='default', max_length=16, verbose_name='Тип тарифа'),
        ),
    ]
