# Generated by Django 4.0.6 on 2022-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_remove_citytoprice_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytoprice',
            name='prices',
            field=models.ManyToManyField(blank=True, to='tariffs.pricetocarclass'),
        ),
        migrations.AlterField(
            model_name='globaladdresstoprice',
            name='prices',
            field=models.ManyToManyField(blank=True, to='tariffs.pricetocarclass'),
        ),
    ]
