# Generated by Django 4.0.6 on 2022-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_alter_citytoprice_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Название'),
        ),
    ]
