# Generated by Django 4.0.6 on 2022-08-15 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_city_center_alter_cityzone_color'),
        ('tariffs', '0003_intracitytariff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intracitytariff',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='pricetocarclass',
            name='price',
        ),
        migrations.AddField(
            model_name='pricetocarclass',
            name='customer_price',
            field=models.IntegerField(default=0, verbose_name='Цена заказчика'),
        ),
        migrations.AddField(
            model_name='pricetocarclass',
            name='driver_price',
            field=models.IntegerField(default=0, verbose_name='Цена водителя'),
        ),
        migrations.CreateModel(
            name='ZoneToPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.ManyToManyField(to='tariffs.pricetocarclass', verbose_name='Цены к зоне')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.cityzone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Зона к ценам',
                'verbose_name_plural': 'Зоны к ценам',
                'db_table': 'zone_to_prices',
            },
        ),
        migrations.CreateModel(
            name='ServiceToPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=128, verbose_name='Услуга')),
                ('prices', models.ManyToManyField(to='tariffs.pricetocarclass', verbose_name='Услуга к цене')),
            ],
            options={
                'verbose_name': 'Услуга к ценам',
                'verbose_name_plural': 'Услуги к ценам',
                'db_table': 'service_to_price',
            },
        ),
        migrations.AddField(
            model_name='intracitytariff',
            name='service_prices',
            field=models.ManyToManyField(to='tariffs.servicetoprice', verbose_name='Цены к услугам'),
        ),
        migrations.AddField(
            model_name='intracitytariff',
            name='zone_prices',
            field=models.ManyToManyField(to='tariffs.zonetoprice', verbose_name='Цены к зонам'),
        ),
    ]
