# Generated by Django 4.0.6 on 2022-09-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_bankmodel_rename_user_company_owner_and_more'),
        ('tariffs', '0004_alter_tariff_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='companies',
            field=models.ManyToManyField(blank=True, to='profile.company', verbose_name='Компании'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступен?'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='type',
            field=models.CharField(default='Основной', max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
