# Generated by Django 4.0.6 on 2022-08-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_city_center_alter_cityzone_color'),
        ('tariffs', '0004_remove_intracitytariff_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intracitytariff',
            name='zone',
        ),
        migrations.AddField(
            model_name='intracitytariff',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='Город'),
        ),
    ]
