# Generated by Django 4.0.6 on 2022-08-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_address_address_hub_address'),
        ('tariffs', '0005_remove_intracitytariff_zone_intracitytariff_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='address.city', verbose_name='Из грода')),
                ('prices', models.ManyToManyField(to='tariffs.pricetocarclass', verbose_name='Услуга к цене')),
                ('service_prices', models.ManyToManyField(to='tariffs.servicetoprice', verbose_name='Цены к услугам')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='address.city', verbose_name='В город')),
            ],
            options={
                'verbose_name': 'Межгородской тариф',
                'verbose_name_plural': 'Межгородские тарифы',
                'db_table': 'intercity_tariff',
            },
        ),
    ]
