# Generated by Django 4.0.6 on 2022-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_tariff_commission_tariff_companies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='is_commission',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('basic', 'Основной'), ('commission', 'Комиссионный'), ('companies', 'Для компаний')], default='Основной', max_length=32, verbose_name='Тип'),
        ),
    ]
