# Generated by Django 4.0.6 on 2022-08-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0021_globaladdress'),
        ('tariffs', '0007_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalHubZoneToPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.ManyToManyField(to='tariffs.pricetocarclass', verbose_name='Цены к зоне')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.hubzone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Зона хаба к ценам',
                'verbose_name_plural': 'Зоны хаба к ценам',
                'db_table': 'additional_hubzone_to_price',
            },
        ),
        migrations.CreateModel(
            name='HubToPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_hubzone_prices', models.ManyToManyField(to='tariffs.additionalhubzonetoprice', verbose_name='Добавочная стоимость к зонам хаба')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.hub', verbose_name='Хаб')),
                ('prices', models.ManyToManyField(to='tariffs.pricetocarclass', verbose_name='Цены к классу авто')),
            ],
            options={
                'verbose_name': 'Хаб к ценам',
                'verbose_name_plural': 'Хабы у ценам',
                'db_table': 'hub_to_price',
            },
        ),
        migrations.RemoveField(
            model_name='intercitytariff',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='intracitytariff',
            name='city',
        ),
        migrations.RemoveField(
            model_name='intracitytariff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='intracitytariff',
            name='type',
        ),
        migrations.RemoveField(
            model_name='intracitytariff',
            name='zone_prices',
        ),
        migrations.AddField(
            model_name='tariff',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубль'), ('eur', 'Евро'), ('usd', 'Доллар'), ('cny', 'Юани')], default='rub', max_length=5, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_commission',
            field=models.BooleanField(default=False, verbose_name='Комиссионный?'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='ZoneToPrice',
        ),
        migrations.AddField(
            model_name='intracitytariff',
            name='hub_to_prices',
            field=models.ManyToManyField(to='tariffs.hubtoprice', verbose_name='Цены к зонам'),
        ),
    ]
