# Generated by Django 4.0.6 on 2022-10-01 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0008_alter_tariff_title_alter_tariff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее изменение'),
        ),
    ]
