# Generated by Django 4.0.6 on 2022-08-25 08:44

import api.tariffs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0008_additionalhubzonetoprice_hubtoprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='lifetime',
            field=models.DateTimeField(default=api.tariffs.models.tariff_derault_timelife, verbose_name='Срок жизни'),
        ),
    ]
