# Generated by Django 4.0.6 on 2022-08-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0009_tariff_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Название'),
        ),
    ]
