# Generated by Django 4.0.6 on 2022-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0010_alter_tariff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercitytariff',
            name='service_prices',
        ),
        migrations.AddField(
            model_name='tariff',
            name='services',
            field=models.ManyToManyField(to='tariffs.servicetoprice', verbose_name='Цены к услугам'),
        ),
        migrations.AlterField(
            model_name='pricetocarclass',
            name='customer_price',
            field=models.IntegerField(blank=True, default=800, null=True, verbose_name='Цена заказчика'),
        ),
        migrations.AlterField(
            model_name='pricetocarclass',
            name='driver_price',
            field=models.IntegerField(default=600, verbose_name='Цена водителя'),
        ),
    ]
