# Generated by Django 4.0.6 on 2022-10-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_globaladdress_address'),
        ('tariffs', '0011_hubtopricemodel_intercitytariff_hubs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HubToPriceModel',
            new_name='HubsToPriceModel',
        ),
    ]
