# Generated by Django 4.0.6 on 2022-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0011_remove_intercitytariff_service_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetoprice',
            name='type',
            field=models.CharField(choices=[('default', 'Стандартный'), ('custom', 'Не стандартный')], default='default', max_length=24, verbose_name='Тип услуги'),
        ),
    ]
