# Generated by Django 4.0.6 on 2022-10-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0012_rename_hubtopricemodel_hubstopricemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercitytariff',
            old_name='hubs',
            new_name='hub',
        ),
    ]
