# Generated by Django 4.0.6 on 2022-10-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_cityzoneintracitymodel'),
        ('tariffs', '0014_rename_hubs_hubstopricemodel_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intracitytariff',
            name='city_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.cityzoneintracitymodel'),
        ),
    ]
