# Generated by Django 4.0.6 on 2022-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0015_intracitytariff_city_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='intracitytariff',
            name='city_price',
            field=models.IntegerField(default=0, verbose_name='Цена по городу'),
        ),
    ]
