# Generated by Django 4.0.6 on 2022-08-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0016_remove_servicetoprice_service_servicetoprice_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetoprice',
            name='type',
        ),
        migrations.AddField(
            model_name='servicetoprice',
            name='slug',
            field=models.CharField(default='', max_length=128, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='pricetocarclass',
            name='car_class',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('comfort', 'Комфорт'), ('minivan', 'Минивен'), ('business', 'Бизнес'), ('representative', 'Представительский'), ('suv', 'SUV'), ('minibus', 'Микроавтобус'), ('minivan_business', 'Минивен Бизнес'), ('minibus_business', 'Микроавтобус Бизнес'), ('bus30', 'Автобус 30+'), ('bus43', 'Автобус 43+'), ('bus50', 'Автобус 50+')], max_length=32, verbose_name='Класс автомобиля'),
        ),
        migrations.AlterField(
            model_name='pricetocarclass',
            name='customer_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена заказчика'),
        ),
        migrations.AlterField(
            model_name='pricetocarclass',
            name='driver_price',
            field=models.IntegerField(default=0, verbose_name='Цена водителя'),
        ),
        migrations.AlterField(
            model_name='servicetoprice',
            name='prices',
            field=models.ManyToManyField(blank=True, to='tariffs.pricetocarclass', verbose_name='Услуга к цене'),
        ),
    ]
