# Generated by Django 4.0.6 on 2022-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0017_remove_servicetoprice_type_servicetoprice_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetocarclass',
            name='car_class',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('comfort', 'Комфорт'), ('minivan', 'Минивен'), ('business', 'Бизнес'), ('representative', 'Представительский'), ('suv', 'SUV'), ('minibus', 'Микроавтобус'), ('minivan_business', 'Минивен Бизнес'), ('minibus_business', 'Микроавтобус Бизнес'), ('bus30', 'Автобус 30+'), ('bus43', 'Автобус 43+'), ('bus50', 'Автобус 50+')], max_length=64, verbose_name='Класс автомобиля'),
        ),
    ]
