# Generated by Django 4.0.6 on 2022-10-15 11:02

import api.tariffs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0017_remove_intracitytariff_city_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intracitytariff',
            name='city_price',
        ),
        migrations.AddField(
            model_name='intracitytariff',
            name='prices',
            field=models.ManyToManyField(default=api.tariffs.models.default_price_to_car_class, to='tariffs.pricetocarclass', verbose_name='Цены к классу авто'),
        ),
    ]
