# Generated by Django 4.0.6 on 2022-08-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0018_alter_pricetocarclass_car_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intracitytariff',
            name='service_prices',
        ),
        migrations.AlterField(
            model_name='pricetocarclass',
            name='customer_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена заказчика'),
        ),
    ]
