# Generated by Django 4.0.6 on 2022-08-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0019_remove_intracitytariff_service_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='intercity_tariff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.intercitytariff', verbose_name='межгородской тариф'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='intracity_tariff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.intracitytariff', verbose_name='Внутригородской тариф'),
        ),
    ]
