# Generated by Django 4.0.6 on 2022-07-26 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('financial_turnover', models.IntegerField(default=0, verbose_name='Финансовый оборот')),
                ('status', models.CharField(choices=[('constant', 'Постоянный'), ('default', 'Обычный')], default='default', max_length=12, verbose_name='Статус')),
                ('gen_director_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('gen_director_surname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
                ('gen_director_patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Адрес')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'contractor',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('constant', 'Постоянный'), ('default', 'Обычный')], default='default', max_length=12, verbose_name='Статус')),
                ('financial_turnover', models.IntegerField(default=0, verbose_name='Финансовый оборот')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
    ]
