# Generated by Django 4.0.6 on 2022-08-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
