# Generated by Django 4.0.6 on 2022-08-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_remove_address_address_remove_hub_address_and_more'),
        ('cars', '0002_alter_car_car_class'),
        ('profile', '0007_remove_client_locality_driver_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='locality',
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят')], default='busy', max_length=12, verbose_name='Статус'),
        ),
    ]
