# Generated by Django 4.0.6 on 2022-08-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_remove_driver_locality_driver_city_alter_driver_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Водительское удостоверение'),
        ),
    ]
