# Generated by Django 4.0.6 on 2022-08-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_remove_driver_car_alter_driver_driving_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='passport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Паспорт'),
        ),
    ]
