# Generated by Django 4.0.6 on 2022-07-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=256, verbose_name='Адрес')),
                ('driving_license', models.CharField(max_length=10, verbose_name='Права')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят')], max_length=12, verbose_name='Статус')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'db_table': 'driver',
            },
        ),
    ]
