# Generated by Django 4.0.6 on 2022-08-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
