# Generated by Django 4.0.6 on 2022-07-28 11:16

import api.orders.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0002_company_delete_contractor'),
        ('address', '0002_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(choices=[('business', 'Бизнес'), ('standart', 'Стандарт')], max_length=12, verbose_name='Класс автомобиля')),
                ('client_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя клиента')),
                ('client_surname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия клиента')),
                ('client_patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество клиента')),
                ('clinet_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Телефон клиента')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('time', models.DateField(default=django.utils.timezone.now, verbose_name='Время заказа')),
                ('price', models.IntegerField(default=api.orders.models.claculate_price, verbose_name='Цена')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.company', verbose_name='Заказчик')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='address.address', verbose_name='Из')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='address.address', verbose_name='В')),
            ],
        ),
    ]
