# Generated by Django 4.0.6 on 2022-08-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0007_tariff'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='intercity_tariff',
        ),
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='intracity_tariff',
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='tariff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff', verbose_name='тариф'),
        ),
    ]
