# Generated by Django 4.0.6 on 2022-08-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetailmodel_intercity_tariff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_class',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('comfort', 'Комфорт'), ('minivan', 'Минивен'), ('business', 'Бизнес'), ('representative', 'Представительский'), ('suv', 'SUV'), ('minibus', 'Микроавтобус'), ('minivan_business', 'Минивен Бизнес'), ('minibus_business', 'Микроавтобус Бизнес'), ('bus30', 'Автобус 30+'), ('bus43', 'Автобус 43+'), ('bus50', 'Автобус 50+')], max_length=24, verbose_name='Класс автомобиля'),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='car_class',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('comfort', 'Комфорт'), ('minivan', 'Минивен'), ('business', 'Бизнес'), ('representative', 'Представительский'), ('suv', 'SUV'), ('minibus', 'Микроавтобус'), ('minivan_business', 'Минивен Бизнес'), ('minibus_business', 'Микроавтобус Бизнес'), ('bus30', 'Автобус 30+'), ('bus43', 'Автобус 43+'), ('bus50', 'Автобус 50+')], max_length=32, verbose_name='Класс авто'),
        ),
    ]
