# Generated by Django 4.0.6 on 2022-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=128, verbose_name='Страна')),
                ('region', models.CharField(max_length=128, null=True, verbose_name='Регион')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('street', models.CharField(max_length=128, verbose_name='Улица')),
                ('number', models.CharField(default='1', max_length=12, verbose_name='Номер дома')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
