# Generated by Django 4.0.6 on 2022-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='slug',
            field=models.SlugField(default='', verbose_name='Слаг'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='address_city',
        ),
    ]
