# Generated by Django 4.0.6 on 2022-08-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_city_coordinate_pricetocarclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityzone',
            name='prices',
        ),
        migrations.AddField(
            model_name='address',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.coordinate'),
        ),
        migrations.DeleteModel(
            name='PriceToCarClass',
        ),
    ]
