# Generated by Django 4.0.6 on 2022-09-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_hub_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
