# Generated by Django 4.0.6 on 2022-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_hub_slug_alter_hub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Слаг'),
        ),
    ]
