# Generated by Django 4.0.6 on 2022-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_remove_cityzone_prices_address_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityzone',
            name='color',
            field=models.CharField(choices=[('red', 'Красная'), ('green', 'Зеленая'), ('yellow', 'Желтая'), ('blue', 'Синяя'), ('orange', 'Оранжевая')], max_length=12, verbose_name='Цвет'),
        ),
        migrations.AddConstraint(
            model_name='coordinate',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_coords'),
        ),
    ]
