# Generated by Django 4.0.6 on 2022-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_hub_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubzone',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
        ),
    ]
