# Generated by Django 4.0.6 on 2022-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_cityzone_color_coordinate_unique_coords'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coordinate',
            name='unique_coords',
        ),
        migrations.AddConstraint(
            model_name='coordinate',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_coords'),
        ),
    ]
