# Generated by Django 4.0.6 on 2022-08-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_remove_coordinate_unique_coords_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cityzone',
            table='city_zone',
        ),
        migrations.AlterModelTable(
            name='coordinate',
            table='city_zone_coordinate',
        ),
    ]
