# Generated by Django 4.0.6 on 2022-08-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_cityzone_table_alter_coordinate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='address.coordinate', verbose_name='Координаты'),
        ),
    ]
