# Generated by Django 4.0.6 on 2022-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_globaladdress_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityZoneIntracityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Красная'), ('green', 'Зеленая'), ('yellow', 'Желтая'), ('blue', 'Синяя')], max_length=12, verbose_name='Цвет')),
                ('coordinates', models.ManyToManyField(to='address.coordinate')),
            ],
            options={
                'verbose_name': 'Зона города (Внутригород)',
                'verbose_name_plural': 'Зоны городов (Внутригород)',
                'db_table': 'city_zone__intracity',
            },
        ),
    ]
