# Generated by Django 4.0.6 on 2022-10-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_cityzoneintracitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.cityzoneintracitymodel'),
        ),
        migrations.AlterField(
            model_name='cityzoneintracitymodel',
            name='coordinates',
            field=models.ManyToManyField(to='address.coordinate', verbose_name='координаты'),
        ),
    ]
