# Generated by Django 4.0.6 on 2022-10-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_city_zone_alter_cityzoneintracitymodel_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityzoneintracitymodel',
            name='color',
        ),
    ]
