# Generated by Django 4.0.6 on 2022-08-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_alter_address_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.coordinate'),
        ),
        migrations.AlterField(
            model_name='cityzone',
            name='color',
            field=models.CharField(choices=[('red', 'Красная'), ('green', 'Зеленая'), ('yellow', 'Желтая'), ('blue', 'Синяя')], max_length=12, verbose_name='Цвет'),
        ),
    ]
