# Generated by Django 4.0.6 on 2022-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='descrition',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
