# Generated by Django 4.0.6 on 2022-08-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_hub_descrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='number',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='street',
        ),
    ]
