# Generated by Django 4.0.6 on 2022-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_remove_hub_number_remove_hub_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='hub',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Улица'),
        ),
    ]
