# Generated by Django 4.0.6 on 2022-08-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_address_address_hub_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='number',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='street',
        ),
    ]
