# Generated by Django 4.0.6 on 2022-08-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_remove_address_address_remove_hub_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub',
            old_name='descrition',
            new_name='description',
        ),
    ]
