# Generated by Django 4.0.6 on 2022-08-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0018_rename_descrition_hub_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Красная'), ('green', 'Зеленая'), ('yellow', 'Желтая'), ('blue', 'Синяя')], max_length=12, verbose_name='Цвет')),
                ('coordinates', models.ManyToManyField(to='address.coordinate')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.hub', verbose_name='Хаб')),
            ],
            options={
                'verbose_name': 'Зона хаба',
                'verbose_name_plural': 'Зоны хабов',
                'db_table': 'рги_zone',
            },
        ),
    ]
