# Generated by Django 4.0.6 on 2022-08-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_hubzone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hubzone',
            table='hub_zone',
        ),
    ]
