# Generated by Django 4.0.6 on 2022-08-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_alter_hubzone_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAddress',
            fields=[
                ('hub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.hub')),
            ],
            options={
                'verbose_name': 'Глобальный адрес',
                'verbose_name_plural': 'Глобальные адреса',
                'db_table': 'address_globaladdress',
            },
            bases=('address.hub',),
        ),
    ]
